trigger: none

pr:
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: infra-templates
      type: git
      name: Orano-Med/oranomed-infrastructure-repo
      ref: refs/heads/reusable-template

pool: jumphost-dev-agent

variables:
  - group: sonarqube-frontend-variables
  - name: buildVersion
    value: "$(Date:yyyyMMdd).$(Rev:.r)"

stages:
  - stage: SecurityScan
    displayName: "GitLeak & Trivy Scan"
    jobs:
      - template: templates/security-scan.yml@infra-templates
        parameters:
          pool: jumphost-dev-agent
          gitleaksConfigType: "default"
          gitleaksScanMode: "directory"
          trivyScanners: "vuln,misconfig,secret,license"
          trivySeverities: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          trivyFailThreshold: "HIGH"

  - stage: SonarQubeAnalysis
    displayName: "SonarQube Scan"
    dependsOn: SecurityScan
    condition: succeeded()
    jobs:
      - template: templates/sonarqube-analysis.yml@infra-templates
        parameters:
          pool: jumphost-dev-agent
          sonarConnection: "$(frontendSonarConnection)"
          sonarProjectKey: "$(frontendSonarProjectKey)"
          sonarProjectName: "PR-1551-OranoMed-frontend-ReactJs"
          sonarToken: "$(sonarToken)"
          jdkVersion: "JAVA_HOME_17_X64"
