trigger:
  branches:
    include:
      - staging
  paths:
    exclude:
      - README.md

pr: none

resources:
  repositories:
    - repository: infra-templates
      type: git
      name: Orano-Med/oranomed-infrastructure-repo
      ref: refs/heads/reusable-template

pool: jumphost-prod-agent

variables:
  - name: COMMIT_HASH
    value: $[ substring(variables['Build.SourceVersion'], 0, 7) ]
  - group: stage-frontend

steps:
  - template: templates/notify-teams.yml@infra-templates
    parameters:
      webhookUrl: $(TEAMS_WEBHOOK_URL)
      status: "started"

  - script: |
      rm -rf .env
      echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" >> .env
      echo "VITE_API_VERSION=${VITE_API_VERSION}" >> .env
      echo "VITE_APP_ENV=${VITE_APP_ENV}" >> .env
      echo "VITE_APP_NAME=${VITE_APP_NAME}" >> .env
      echo "VITE_APP_VERSION=${VITE_APP_VERSION}" >> .env
      echo "VITE_AUTH_REFRESH_TOKEN_KEY=${VITE_AUTH_REFRESH_TOKEN_KEY}" >> .env
      echo "VITE_AUTH_TOKEN_KEY=${VITE_AUTH_TOKEN_KEY}" >> .env
      echo "VITE_FEATURE_FLAG_EXPERIMENTAL=${VITE_FEATURE_FLAG_EXPERIMENTAL}" >> .env
      echo "VITE_LOG_LEVEL=${VITE_LOG_LEVEL}" >> .env
      echo "VITE_REACT_QUERY_CACHE_TIME=${VITE_REACT_QUERY_CACHE_TIME}" >> .env
      echo "VITE_REACT_QUERY_MAX_RETRY_DELAY=${VITE_REACT_QUERY_MAX_RETRY_DELAY}" >> .env
      echo "VITE_REACT_QUERY_RETRY=${VITE_REACT_QUERY_RETRY}" >> .env
      echo "VITE_REACT_QUERY_RETRY_DELAY=${VITE_REACT_QUERY_RETRY_DELAY}" >> .env
      echo "VITE_REACT_QUERY_STALE_TIME=${VITE_REACT_QUERY_STALE_TIME}" >> .env
      echo "VITE_SOCKET_URL=${VITE_SOCKET_URL}" >> .env
      echo "VITE_SENTRY_DSN=${VITE_SENTRY_DSN}" >> .env
      ehco "VITE_CRYPTO_SECRET"=${VITE_CRYPTO_SECRET} >> .env
    displayName: "Create ENV file"

  - template: templates/docker-build-push.yml@infra-templates
    parameters:
      environment: "prod"
      registry: $(REGISTRY)
      commitHash: $(COMMIT_HASH)
      useCompose: false
      dockerfile: "Dockerfile.prod"
      imageName: "orano_prod_frontend"

  - template: templates/helm-update-deploy.yml@infra-templates
    parameters:
      commitHash: $(COMMIT_HASH)
      helmChartPath: "/home/jumpboxadmin/k8s-files/helm-chart-frontend"
      deployments:
        - frontend

  - template: templates/notify-teams.yml@infra-templates
    parameters:
      webhookUrl: $(TEAMS_WEBHOOK_URL)
      status: "succeeded"

  - template: templates/notify-teams.yml@infra-templates
    parameters:
      webhookUrl: $(TEAMS_WEBHOOK_URL)
      status: "failed"

  - template: templates/notify-teams.yml@infra-templates
    parameters:
      webhookUrl: $(TEAMS_WEBHOOK_URL)
      status: "stopped"
