/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as UserManagementRouteImport } from "./routes/user-management";
import { Route as TemplatesRouteImport } from "./routes/templates";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as RbacRouteImport } from "./routes/rbac";
import { Route as ProjectFoldersRouteImport } from "./routes/project-folders";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as MasterDataRouteImport } from "./routes/master-data";
import { Route as DataValidateRouteImport } from "./routes/data-validate";
import { Route as DataUploadRouteImport } from "./routes/data-upload";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";

const UserManagementRoute = UserManagementRouteImport.update({
  id: "/user-management",
  path: "/user-management",
  getParentRoute: () => rootRouteImport,
} as any);
const TemplatesRoute = TemplatesRouteImport.update({
  id: "/templates",
  path: "/templates",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const RbacRoute = RbacRouteImport.update({
  id: "/rbac",
  path: "/rbac",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectFoldersRoute = ProjectFoldersRouteImport.update({
  id: "/project-folders",
  path: "/project-folders",
  getParentRoute: () => rootRouteImport,
} as any);
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
} as any);
const MasterDataRoute = MasterDataRouteImport.update({
  id: "/master-data",
  path: "/master-data",
  getParentRoute: () => rootRouteImport,
} as any);
const DataValidateRoute = DataValidateRouteImport.update({
  id: "/data-validate",
  path: "/data-validate",
  getParentRoute: () => rootRouteImport,
} as any);
const DataUploadRoute = DataUploadRouteImport.update({
  id: "/data-upload",
  path: "/data-upload",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/data-upload": typeof DataUploadRoute;
  "/data-validate": typeof DataValidateRoute;
  "/master-data": typeof MasterDataRoute;
  "/notifications": typeof NotificationsRoute;
  "/project-folders": typeof ProjectFoldersRoute;
  "/rbac": typeof RbacRoute;
  "/settings": typeof SettingsRoute;
  "/templates": typeof TemplatesRoute;
  "/user-management": typeof UserManagementRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/data-upload": typeof DataUploadRoute;
  "/data-validate": typeof DataValidateRoute;
  "/master-data": typeof MasterDataRoute;
  "/notifications": typeof NotificationsRoute;
  "/project-folders": typeof ProjectFoldersRoute;
  "/rbac": typeof RbacRoute;
  "/settings": typeof SettingsRoute;
  "/templates": typeof TemplatesRoute;
  "/user-management": typeof UserManagementRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/data-upload": typeof DataUploadRoute;
  "/data-validate": typeof DataValidateRoute;
  "/master-data": typeof MasterDataRoute;
  "/notifications": typeof NotificationsRoute;
  "/project-folders": typeof ProjectFoldersRoute;
  "/rbac": typeof RbacRoute;
  "/settings": typeof SettingsRoute;
  "/templates": typeof TemplatesRoute;
  "/user-management": typeof UserManagementRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/data-upload"
    | "/data-validate"
    | "/master-data"
    | "/notifications"
    | "/project-folders"
    | "/rbac"
    | "/settings"
    | "/templates"
    | "/user-management"
    | "/auth/forgot-password"
    | "/auth/login";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/data-upload"
    | "/data-validate"
    | "/master-data"
    | "/notifications"
    | "/project-folders"
    | "/rbac"
    | "/settings"
    | "/templates"
    | "/user-management"
    | "/auth/forgot-password"
    | "/auth/login";
  id:
    | "__root__"
    | "/"
    | "/data-upload"
    | "/data-validate"
    | "/master-data"
    | "/notifications"
    | "/project-folders"
    | "/rbac"
    | "/settings"
    | "/templates"
    | "/user-management"
    | "/auth/forgot-password"
    | "/auth/login";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DataUploadRoute: typeof DataUploadRoute;
  DataValidateRoute: typeof DataValidateRoute;
  MasterDataRoute: typeof MasterDataRoute;
  NotificationsRoute: typeof NotificationsRoute;
  ProjectFoldersRoute: typeof ProjectFoldersRoute;
  RbacRoute: typeof RbacRoute;
  SettingsRoute: typeof SettingsRoute;
  TemplatesRoute: typeof TemplatesRoute;
  UserManagementRoute: typeof UserManagementRoute;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/user-management": {
      id: "/user-management";
      path: "/user-management";
      fullPath: "/user-management";
      preLoaderRoute: typeof UserManagementRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/templates": {
      id: "/templates";
      path: "/templates";
      fullPath: "/templates";
      preLoaderRoute: typeof TemplatesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rbac": {
      id: "/rbac";
      path: "/rbac";
      fullPath: "/rbac";
      preLoaderRoute: typeof RbacRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project-folders": {
      id: "/project-folders";
      path: "/project-folders";
      fullPath: "/project-folders";
      preLoaderRoute: typeof ProjectFoldersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notifications": {
      id: "/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof NotificationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/master-data": {
      id: "/master-data";
      path: "/master-data";
      fullPath: "/master-data";
      preLoaderRoute: typeof MasterDataRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/data-validate": {
      id: "/data-validate";
      path: "/data-validate";
      fullPath: "/data-validate";
      preLoaderRoute: typeof DataValidateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/data-upload": {
      id: "/data-upload";
      path: "/data-upload";
      fullPath: "/data-upload";
      preLoaderRoute: typeof DataUploadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/auth/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataUploadRoute: DataUploadRoute,
  DataValidateRoute: DataValidateRoute,
  MasterDataRoute: MasterDataRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectFoldersRoute: ProjectFoldersRoute,
  RbacRoute: RbacRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UserManagementRoute: UserManagementRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
